// front/src/components/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav-bar',
  standalone: false,
  
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.scss'
})
export class NavBarComponent {
  isSidebarOpen = false;

  toggleSidebar() {
    this.isSidebarOpen = !this.isSidebarOpen;
  }
}

<nav class="navbar">
    <img src="../../assets/images/logo.png" alt="Logo" />
    <div class="nav-links">
      <a href="#">Home</a>
      <a href="#">Partneri</a>
      <a href="#">O nama</a>
      <a href="#">Novosti</a>
      <a href="#">Razmena</a>
    </div>
    <div class="menu-icon" (click)="toggleSidebar()">
      <button>Click</button>
    </div>
  </nav>
  
  <div class="sidebar" [class.open]="isSidebarOpen">
    <a href="#">Home</a>
    <a href="#">Partneri</a>
    <a href="#">O nama</a>
    <a href="#">Novosti</a>
    <a href="#">Razmena</a>
  </div>

// frontend/src/components/Navbar/Navbar.tsx
import { useState } from 'react';
import './NavBar.css';
import logo from "../../assets/images/logo.png"

const NavBar = () => {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <>
      <nav className="navbar">
        <img src={logo} alt="Logo" />
        <div className="nav-links">
          <a href="#">Home</a>
          <a href="#">Partneri</a>
          <a href="#">O nama</a>
          <a href="#">Novosti</a>
          <a href="#">Razmena</a>
        </div>
        <div className="menu-icon" onClick={toggleSidebar}>
          <button>Click</button>
        </div>
      </nav>

      <div className={`sidebar ${isSidebarOpen ? 'open' : ''}`}>
        <a href="#">Home</a>
        <a href="#">Partneri</a>
        <a href="#">O nama</a>
        <a href="#">Novosti</a>
        <a href="#">Razmena</a>
      </div>
    </>
  );
};

export default NavBar;
